import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import Footer from "@/components/layout/Footer/Footer";
import 'swiper/css';
import 'swiper/css/free-mode';
import 'swiper/css/thumbs';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import Provider from "@/components/shared/Provider";

import { Exo_2 } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo_2({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-exo', 
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

  <body className={`${exo.className} min-h-full flex flex-col`}>
    <main>
  <Provider> 
      <Navbar></Navbar>
<ToastContainer position="top-right" />         {children}
        <Footer></Footer>
    </Provider>
</main>
</body>

    </html>
  );
}
